name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install and build
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test
